### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by awitherow** [preichenberger/go-coinbase-exchange#13]
According to the Readme, it says the build is failing.

Is this software stable to use?

**Comment by awitherow** [comment]
@preichenberger hello

**Comment by preichenberger** [comment]
Hi, unfortunately the tests use the GDAX sandbox (https://docs.gdax.com/#sandbox) however, it looks like it's been down for some time. I asked them if they'll be up, I'll update if goes up.

**Comment by awitherow** [comment]
@preichenberger thanks! Good to know 👍
