### ISSUE TITLE
should this project use decimals instead of floats?

### ISSUE THREAD

**Issue by tmc** [preichenberger/go-coinbase-exchange#18]
https://github.com/cockroachdb/apd would be a good candidate

**Comment by preichenberger** [comment]
Agreed

**Comment by ColtonProvias** [comment]
The only stumbling block I can see here is that not everybody uses apd. There appear to be more using https://github.com/shopspring/decimal, for example.

It may be best to take a framework agnostic approach and maintain the values as strings. The developer can then use their choice of library in handling them.

**Comment by preichenberger** [comment]
After thinking about this, I think this is left to the user. If there are any ideas on how to support different libraries without being too intrusive to the core, I'm all for it.
