### ISSUE TITLE
Accessing sctruct members of type Time

### ISSUE THREAD

**Issue by adamrigg** [preichenberger/go-coinbase-exchange#24]
How are sctruct members of type Time accessed in go-coinbase-exchange? Is there some way to treat these as standard golang time.Time structs in the existing implementation? Would that require a unique interface or new set of functions within time.go? I'm a bit confused when it comes to the declaration of type Time in this project's time.go.

For example, when modifying the List Account Ledger example from Readme.md (or the main Github page of the project), I wanted to include some useful information about transaction times in a human-readable format using the following line of code:
`fmt.Printf(e.CreatedAt.Format("2006-01-02 15:04:05.999999+00"))`

This throws the following compiler error:
`e.CreatedAt.Format undefined (type coinbase.Time has no field or method Format)`

I can see the struct members `wall, ext and loc` by printing `e.CreatedAt` (where `e` is a ledger range) by replacing the print statement above with the following:
`fmt.Printf("%#v", e.CreatedAt)`

But I'm not quite sure how to parse the resulting string so that the coinbase.Time variables can be treated as standard golang or UNIX times.

This project could use some development with respect to documenting the functions whose combined prototypes and raw code are kind of "self-documenting" rather than verbose. I would be happy to contribute something in that regard should someone point me in the right direction with the underlying fundamentals of go at play here.

Given the limited number of contributors here, I've also posted the question on StackOverflow in a more abstract way (with respect to computer programming terminology) which addresses the more general case of type wrapping/extension:
https://stackoverflow.com/questions/46181419/type-wrapping-of-non-atomic-types-in-golang

**Comment by adamrigg** [comment]
One option for this particular case would be to include the following line of code (or something else which works) in the Ledger example:
`fmt.Printf((time.Time(e.CreatedAt)).Format("2006-01-02 15:04:05.999999+00"))`
(from my accepted StackOverflow answer in the question I posted there and linked to above)

**Comment by preichenberger** [comment]
Added this: https://github.com/preichenberger/go-coinbase-exchange/commit/ecf01c862e8ca972dc307284f9584f8d08faf7c0
