### ISSUE TITLE
Testing trouble

### ISSUE THREAD

**Issue by ivank2139** [preichenberger/go-coinbase-exchange#29]
I am having trouble using the library.  Specifically when testing I keep getting the Invalid API Key or some related error depending on exactly how the tests are run.  Can you assist?

env | grep COINBASE
TEST_COINBASE_OFFSET=+5
TEST_COINBASE_PASSPHRASE=5...e
TEST_COINBASE_SECRET=V...==
TEST_COINBASE_KEY=f...2
ivan@lenii:~/workspace-go/src/go-coinbase-exchange$ go test
--- FAIL: TestGetAccounts (0.37s)
	account_test.go:12: Invalid API Key
--- FAIL: TestGetAccount (0.24s)
	account_test.go:27: Invalid API Key
--- FAIL: TestListAccountLedger (0.24s)
	account_test.go:47: Invalid API Key
--- FAIL: TestListHolds (0.24s)
	account_test.go:72: Invalid API Key
--- FAIL: TestListFills (0.48s)
	fill_test.go:15: Invalid API Key
	fill_test.go:30: Invalid API Key
--- FAIL: TestCreateLimitOrders (0.24s)
	order_test.go:20: Invalid API Key
	order_test.go:24: No create id found
	order_test.go:30: Price not equal
--- FAIL: TestCreateMarketOrders (0.24s)
	order_test.go:47: Invalid API Key
	order_test.go:51: No create id found
	order_test.go:57: Size not equal
--- FAIL: TestCancelOrder (0.24s)
	order_test.go:67: Invalid API Key
--- FAIL: TestGetOrder (0.55s)
	order_test.go:92: Invalid API Key
	order_test.go:97: Invalid API Key
--- FAIL: TestListOrders (0.50s)
	order_test.go:112: Invalid API Key
	order_test.go:125: Invalid API Key
FAIL
exit status 1
FAIL	go-coinbase-exchange	6.774s

If I run an individual test I get an error like this one:
account_test.go:12: CB-ACCESS-KEY header is required

I started my own main and this seems to work but the testing is still a mystery to me.

**Comment by preichenberger** [comment]
It uses keys that work with the sandbox: https://public.sandbox.gdax.com
You will also have to have bitcoin and usd in the test account for the tests to pass.
