### ISSUE TITLE
json serialization is not actual

### ISSUE THREAD

**Issue by eugene-korobko** [preichenberger/go-coinbase-exchange#3]
Hi Philip,

Do you know that is tradingview? I'm readingview developer and I'm working in integrating coinbase feed to our feed system and I'm trying to use go-coinbase-exchange project. Unfortunately, it looks to be desolated. For instance, it cannot download products because of json mapping is obsolte and mistatches.
Surely I can clone the repository and develop it locally (this is what I've already started with), however I'd like to make my fixes public and alive, so what do you think about adding me as a developer to the project?

Eugene Korobko
ekorobko@tradingview.com
TradingView developer

**Comment by preichenberger** [comment]
Hi,

I've fixed the products JSON serialization in this release: https://github.com/preichenberger/go-coinbase-exchange/releases/tag/0.2.2

If there are issues/changes you want to make please open a pull request (https://help.github.com/articles/using-pull-requests/) and I can add them to the repo.

Thanks!
